// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CabinRental.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250121155603_UpdateSeed")]
    partial class UpdateSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CabinRental.Models.Cabin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Cabins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cabin Street 1",
                            City = "Bergen",
                            Name = "Lake Cabin",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cabin Street 2",
                            City = "Bergen",
                            Name = "Mountain Cabin",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Cabin Street 3",
                            City = "Bergen",
                            Name = "River Cabin",
                            Price = 3000.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Cabin Street 4",
                            City = "Bergen",
                            Name = "Forrest Cabin",
                            Price = 4000.0
                        });
                });

            modelBuilder.Entity("CabinRental.Models.CabinImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CabinId");

                    b.ToTable("CabinImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CabinId = 1,
                            ImagePath = "/Images/Cabin/Cabin1.webp"
                        },
                        new
                        {
                            Id = 2,
                            CabinId = 1,
                            ImagePath = "/Images/Cabin/Cabin1Interior.webp"
                        },
                        new
                        {
                            Id = 3,
                            CabinId = 2,
                            ImagePath = "/Images/Cabin/Cabin2.webp"
                        },
                        new
                        {
                            Id = 4,
                            CabinId = 2,
                            ImagePath = "/Images/Cabin/Cabin2Interior.webp"
                        },
                        new
                        {
                            Id = 5,
                            CabinId = 3,
                            ImagePath = "/Images/Cabin/Cabin3.webp"
                        },
                        new
                        {
                            Id = 6,
                            CabinId = 3,
                            ImagePath = "/Images/Cabin/Cabin3Interior.webp"
                        },
                        new
                        {
                            Id = 7,
                            CabinId = 4,
                            ImagePath = "/Images/Cabin/Cabin4.webp"
                        },
                        new
                        {
                            Id = 8,
                            CabinId = 4,
                            ImagePath = "/Images/Cabin/Cabin4Interior.webp"
                        });
                });

            modelBuilder.Entity("CabinRental.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CabinRental.Models.CabinImage", b =>
                {
                    b.HasOne("CabinRental.Models.Cabin", "Cabin")
                        .WithMany("Images")
                        .HasForeignKey("CabinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabin");
                });

            modelBuilder.Entity("CabinRental.Models.Cabin", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
