<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <None Include="wwwroot\Images\Cabin\Cabin1.webp" />
      <None Include="wwwroot\Images\Cabin\Cabin2.webp" />
      <None Include="wwwroot\Images\Cabin\Cabin3.webp" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.0" />
      <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.8.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="8.0.0" />
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Areas\Admin\Views\UserManager\CreateUserForm.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Views\UserManager\EditUserForm.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Views\UserManager\ManageUsers.cshtml" />
    </ItemGroup>

</Project>
